/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cozy_home_items.glb -k -s -I -E -T -j -M 
Files: cozy_home_items.glb [738.8MB] > D:\3D Models\CozyHome\cozy_home_items-transformed.glb [14.28MB] (98%)
*/

import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = React.createContext()

export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/cozy_home_items_transformed.glb')
  const instances = React.useMemo(
    () => ({
      SMSofa: nodes.SM_Sofa_1,
      SMSofa1: nodes.SM_Sofa_2,
      SMSofa2: nodes.SM_Sofa_3,
      SMSofa3: nodes.SM_Sofa_4,
      SMPlant: nodes.SM_Plant_1_1,
      SMPlant1: nodes.SM_Plant_1_2,
      SMPlant2: nodes.SM_Plant_1_3,
      SMBed: nodes.SM_Bed_1,
      SMBed1: nodes.SM_Bed_2,
      SMBed2: nodes.SM_Bed_3,
      SMBed3: nodes.SM_Bed_4,
      SMBed4: nodes.SM_Bed_5,
      SMBed5: nodes.SM_Bed_6,
      SMBed6: nodes.SM_Bed_7,
      SMCoffeTable: nodes.SM_Coffe_Table_2,
      SMDecor: nodes.SM_Decor_6_1,
      SMDecor1: nodes.SM_Decor_6_2,
      SMDecor2: nodes.SM_Decor_6_3,
      SMFloorLamp: nodes.SM_Floor_Lamp_1,
      SMFloorLamp1: nodes.SM_Floor_Lamp_2,
      SMFloorLamp2: nodes.SM_Floor_Lamp_3,
      SMFloorLamp3: nodes.SM_Floor_Lamp_4,
      SMCoffeTable1: nodes.SM_Coffe_Table_3_1,
      SMCoffeTable2: nodes.SM_Coffe_Table_3_2,
      SMOpenedBook: nodes.SM_Opened_Book,
      SWoodenTableviejdilodVar: nodes.S_Wooden_Table_viejdi1_lod3_Var1,
      SMOttoman: nodes.SM_Ottoman,
      Ukmlcaoawtier: nodes.ukmlcaoaw_tier_2,
      SMChair: nodes.SM_Chair_2_1,
      SMChair1: nodes.SM_Chair_2_2,
      SMVase: nodes.SM_Vase_9,
      SMDecor3: nodes.SM_Decor_9,
      SMVase1: nodes.SM_Vase_4,
      SMVase2: nodes.SM_Vase_6,
      SMKitchenDecor: nodes.SM_Kitchen_Decor_9_1,
      SMKitchenDecor1: nodes.SM_Kitchen_Decor_9_2,
      Koreanbuddhaironstatue: nodes.korean_buddha_iron_statue,
      Ukkpdhqbwtier: nodes.ukkpdhqbw_tier_2,
      SMuiyvcgffatier: nodes.SM_uiyvcgffa_tier_2,
      Foshaybookcaserackglb: nodes.foshay_bookcase_rack_glb_1,
      Foshaybookcaserackglb1: nodes.foshay_bookcase_rack_glb_2,
      Foshaybookcaserackglb2: nodes.foshay_bookcase_rack_glb_3,
      Foshaybookcaserackglb3: nodes.foshay_bookcase_rack_glb_4,
      Vmjhbixtier: nodes.vmjhbix_tier_2,
      SMSystemA: nodes.SM_System_01_A_1,
      SMSystemA1: nodes.SM_System_01_A_2,
      SMSystemA2: nodes.SM_System_01_A_3,
      SMSystemGLadder: nodes.SM_System_G_Ladder_1,
      SMSystemGLadder1: nodes.SM_System_G_Ladder_2,
      SMApple: nodes.SM_Apple_02,
      SMBooksMix: nodes.SM_Books_Mix_6_1,
      SMBooksMix1: nodes.SM_Books_Mix_6_2,
      SMBooksMix2: nodes.SM_Books_Mix_6_3,
      SMPictureD: nodes.SM_Picture_D_1,
      SMPictureD1: nodes.SM_Picture_D_2,
      SMPictureC: nodes.SM_Picture_C_2,
      SMPictureA: nodes.SM_Picture_A_1,
      SMPictureA1: nodes.SM_Picture_A_2,
      SMPictureB: nodes.SM_Picture_B_2,
      SMBooksMix3: nodes.SM_Books_Mix_2_1,
      SMBooksMix4: nodes.SM_Books_Mix_2_2,
      SMBooksMix5: nodes.SM_Books_Mix_2_3,
      SMBooksMix6: nodes.SM_Books_Mix_2_4,
      SMBooksMix7: nodes.SM_Books_Mix_2_5,
      SMBooksMix8: nodes.SM_Books_Mix_2_6,
      SMBooksMix9: nodes.SM_Books_Mix_2_7,
      SMBooksMix10: nodes.SM_Books_Mix_2_8,
      SMBooksMix11: nodes.SM_Books_Mix_2_9,
      SMBooksMix12: nodes.SM_Books_Mix_2_10,
      SMBooksMix13: nodes.SM_Books_Mix_2_11,
      SMBooksMix14: nodes.SM_Books_Mix_2_12,
      SMBooksMix15: nodes.SM_Books_Mix_2_13,
      SMBuddha: nodes.SM_Buddha,
      SMBoxA: nodes.SM_Box_A,
    }),
    [nodes],
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export default function Model(props) {
  const instances = React.useContext(context)
  return (
    <group {...props} dispose={null}>
      <group name="SM_Sofa" position={[3.1, 0, -1.6]} rotation={[0, -Math.PI / 2, 0]}>
        <instances.SMSofa name="SM_Sofa_1" />
        <instances.SMSofa1 name="SM_Sofa_2" />
        <instances.SMSofa2 name="SM_Sofa_3" />
        <instances.SMSofa3 name="SM_Sofa_4" />
      </group>
      <group name="SM_Plant_1" position={[3.5, 0, -3.4]} rotation={[Math.PI, -1.396, Math.PI]}>
        <instances.SMPlant name="SM_Plant_1_1" />
        <instances.SMPlant1 name="SM_Plant_1_2" />
        <instances.SMPlant2 name="SM_Plant_1_3" />
      </group>
      <group name="SM_Plant_2" position={[0.2, 0, -0.1]}>
        <instances.SMPlant name="SM_Plant_1_1" />
        <instances.SMPlant1 name="SM_Plant_1_2" />
        <instances.SMPlant2 name="SM_Plant_1_3" />
      </group>
      <group name="SM_Bed" position={[-2.3, 0, 3]} rotation={[0, Math.PI / 2, 0]}>
        <instances.SMBed name="SM_Bed_1" />
        <instances.SMBed1 name="SM_Bed_2" />
        <instances.SMBed2 name="SM_Bed_3" />
        <instances.SMBed3 name="SM_Bed_4" />
        <instances.SMBed4 name="SM_Bed_5" />
        <instances.SMBed5 name="SM_Bed_6" />
        <instances.SMBed6 name="SM_Bed_7" />
      </group>
      <instances.SMCoffeTable name="SM_Coffe_Table_2" position={[-3.7, 0, 3.5]} />
      <group name="SM_Decor_6" position={[-3.7, 0.4, 3.5]}>
        <instances.SMDecor name="SM_Decor_6_1" />
        <instances.SMDecor1 name="SM_Decor_6_2" />
        <instances.SMDecor2 name="SM_Decor_6_3" />
      </group>
      <group name="SM_Decor_7" position={[2.3, 0.7, 4.1]}>
        <instances.SMDecor name="SM_Decor_6_1" />
        <instances.SMDecor1 name="SM_Decor_6_2" />
        <instances.SMDecor2 name="SM_Decor_6_3" />
      </group>
      <group name="SM_Floor_Lamp" position={[3.42, 0, 0]} rotation={[0, -0.873, 0]}>
        <instances.SMFloorLamp name="SM_Floor_Lamp_1" />
        <instances.SMFloorLamp1 name="SM_Floor_Lamp_2" />
        <instances.SMFloorLamp2 name="SM_Floor_Lamp_3" />
        <instances.SMFloorLamp3 name="SM_Floor_Lamp_4" />
      </group>
      <group name="SM_Coffe_Table_3" position={[3.1, 0, -3.1]} rotation={[Math.PI, -Math.PI / 6, Math.PI]}>
        <instances.SMCoffeTable1 name="SM_Coffe_Table_3_1" />
        <instances.SMCoffeTable2 name="SM_Coffe_Table_3_2" />
      </group>
      <instances.SMOpenedBook name="SM_Opened_Book" position={[3.1, 0.4, -3.1]} rotation={[Math.PI, -0.175, Math.PI]} />
      <instances.SWoodenTableviejdilodVar name="S_Wooden_Table_viejdi1_lod3_Var1" position={[2.061, 0, 2.075]} />
      <instances.SMOttoman name="SM_Ottoman" position={[2.7, 0, -0.1]} />
      <instances.Ukmlcaoawtier name="ukmlcaoaw_tier_2" position={[3.161, 0, 2.075]} rotation={[Math.PI, 0, Math.PI]} />
      <group name="SM_Chair_2" position={[1.061, 0, 2.175]} rotation={[0, Math.PI / 9, 0]}>
        <instances.SMChair name="SM_Chair_2_1" />
        <instances.SMChair1 name="SM_Chair_2_2" />
      </group>
      <group name="SM_Chair_3" position={[2.361, 0, 3.075]} rotation={[-Math.PI, 1.222, -Math.PI]}>
        <instances.SMChair name="SM_Chair_2_1" />
        <instances.SMChair1 name="SM_Chair_2_2" />
      </group>
      <instances.SMVase name="SM_Vase_9" position={[1.1, 0, 3.8]} />
      <instances.SMDecor3 name="SM_Decor_9" position={[4.1, 0.7, 2.2]} />
      <instances.SMVase1 name="SM_Vase_4" position={[0.1, 0, -3.6]} />
      <instances.SMVase2 name="SM_Vase_6" position={[0.2, 0, -3.7]} />
      <group name="SM_Kitchen_Decor_9" position={[2.061, 0.7, 2.075]}>
        <instances.SMKitchenDecor name="SM_Kitchen_Decor_9_1" />
        <instances.SMKitchenDecor1 name="SM_Kitchen_Decor_9_2" />
      </group>
      <instances.Koreanbuddhaironstatue name="korean_buddha_iron_statue" position={[0.8, 0.4, -3.5]} rotation={[-Math.PI / 2, 0, -0.175]} scale={0.2} />
      <instances.Ukkpdhqbwtier name="ukkpdhqbw_tier_2" position={[3.965, 1.634, -0.776]} rotation={[0, -Math.PI / 2, 0]} />
      <instances.Ukkpdhqbwtier name="ukkpdhqbw_tier_3" position={[3.965, 1.376, 0.043]} rotation={[0, Math.PI / 2, 0]} />
      <instances.SMuiyvcgffatier name="SM_uiyvcgffa_tier_2" position={[0, 0, 0.7]} rotation={[0, -Math.PI / 2, 0]} />
      <group name="foshay_bookcase_rack_glb" position={[0.4, 0, 3.7]} rotation={[-Math.PI, 0, -Math.PI]}>
        <instances.Foshaybookcaserackglb name="foshay_bookcase_rack_glb_1" />
        <instances.Foshaybookcaserackglb1 name="foshay_bookcase_rack_glb_2" />
        <instances.Foshaybookcaserackglb2 name="foshay_bookcase_rack_glb_3" />
        <instances.Foshaybookcaserackglb3 name="foshay_bookcase_rack_glb_4" />
      </group>
      <instances.Vmjhbixtier name="vmjhbix_tier_2" position={[-0.295, 0.787, 0.691]} rotation={[0, -Math.PI / 2, 0]} />
      <group name="SM_System_01_A" position={[3.999, 0, 0.184]} rotation={[0, -Math.PI / 2, 0]}>
        <instances.SMSystemA name="SM_System_01_A_1" />
        <instances.SMSystemA1 name="SM_System_01_A_2" />
        <instances.SMSystemA2 name="SM_System_01_A_3" />
      </group>
      <group name="SM_System_G_Ladder" position={[-1.173, 0, 3.999]} rotation={[0, Math.PI / 2, 0]}>
        <instances.SMSystemGLadder name="SM_System_G_Ladder_1" />
        <instances.SMSystemGLadder1 name="SM_System_G_Ladder_2" />
      </group>
      <instances.SMApple name="SM_Apple_02" position={[-0.41, 1.229, 0.367]} />
      <group name="SM_Books_Mix_6" position={[-0.655, -0.017, 3.383]} rotation={[0, -0.175, 0]}>
        <instances.SMBooksMix name="SM_Books_Mix_6_1" />
        <instances.SMBooksMix1 name="SM_Books_Mix_6_2" />
        <instances.SMBooksMix2 name="SM_Books_Mix_6_3" />
      </group>
      <group name="SM_Picture_D" position={[-1.277, 1.288, 3.999]} rotation={[Math.PI, 0, Math.PI]} scale={3.75}>
        <instances.SMPictureD name="SM_Picture_D_1" />
        <instances.SMPictureD1 name="SM_Picture_D_2" />
      </group>
      <group name="SM_Picture_C" position={[-2.192, 1.271, 4]} rotation={[Math.PI, 0, Math.PI]} scale={1.75}>
        <instances.SMPictureD name="SM_Picture_C_1" />
        <instances.SMPictureC name="SM_Picture_C_2" />
      </group>
      <group name="SM_Picture_A" position={[-2.671, 1.255, 4]} rotation={[Math.PI, 0, Math.PI]}>
        <instances.SMPictureA name="SM_Picture_A_1" />
        <instances.SMPictureA1 name="SM_Picture_A_2" />
      </group>
      <group name="SM_Picture_B" position={[-2.951, 1.25, 4]} rotation={[Math.PI, 0, Math.PI]} scale={2}>
        <instances.SMPictureA name="SM_Picture_B_1" />
        <instances.SMPictureB name="SM_Picture_B_2" />
      </group>
      <group name="SM_Books_Mix_2" position={[-3.221, 0, 1.604]} rotation={[Math.PI, 0, Math.PI]}>
        <instances.SMBooksMix3 name="SM_Books_Mix_2_1" />
        <instances.SMBooksMix4 name="SM_Books_Mix_2_2" />
        <instances.SMBooksMix5 name="SM_Books_Mix_2_3" />
        <instances.SMBooksMix6 name="SM_Books_Mix_2_4" />
        <instances.SMBooksMix7 name="SM_Books_Mix_2_5" />
        <instances.SMBooksMix8 name="SM_Books_Mix_2_6" />
        <instances.SMBooksMix9 name="SM_Books_Mix_2_7" />
        <instances.SMBooksMix10 name="SM_Books_Mix_2_8" />
        <instances.SMBooksMix11 name="SM_Books_Mix_2_9" />
        <instances.SMBooksMix12 name="SM_Books_Mix_2_10" />
        <instances.SMBooksMix13 name="SM_Books_Mix_2_11" />
        <instances.SMBooksMix14 name="SM_Books_Mix_2_12" />
        <instances.SMBooksMix15 name="SM_Books_Mix_2_13" />
      </group>
      <instances.SMBuddha name="SM_Buddha" position={[-3.336, 0, 1.491]} rotation={[Math.PI, -Math.PI / 9, Math.PI]} />
      <instances.SMBoxA name="SM_Box_A" position={[-2.294, 0, 1.47]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/cozy_home_items-transformed.glb')
