/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cozy_home_items_transformed.glb -i 
Files: cozy_home_items_transformed.glb [14.28MB] > D:\Repos\little-room-simulation\little-room-simulation\public\cozy_home_items_transformed-transformed.glb [14.27MB] (0%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CozyhomeItems(props) {
  const { nodes, materials } = useGLTF('/cozy_home_items_t.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[3.1, 0, -1.6]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.SM_Sofa_1.geometry} material={materials.MI_Sofa_SM_Sofa} />
        <mesh geometry={nodes.SM_Sofa_2.geometry} material={materials.MI_Sofa_Pillow_2_SM_Sofa} />
        <mesh geometry={nodes.SM_Sofa_3.geometry} material={materials.MI_Sofa_Pillow_1_SM_Sofa} />
        <mesh geometry={nodes.SM_Sofa_4.geometry} material={materials.PaletteMaterial001} />
      </group>
      <group position={[3.5, 0, -3.4]} rotation={[Math.PI, -1.396, Math.PI]}>
        <mesh geometry={nodes.SM_Plant_1_1.geometry} material={materials.M_Soil} />
        <mesh geometry={nodes.SM_Plant_1_2.geometry} material={materials.M_Plant_1} />
      </group>
      <group position={[-2.3, 0, 3]} rotation={[0, Math.PI / 2, 0]}>
        <mesh geometry={nodes.SM_Bed_1.geometry} material={materials.MI_Bed_Fabric_1_SM_Bed} />
        <mesh geometry={nodes.SM_Bed_2.geometry} material={materials.MI_Bed_Pillow_Fabric_1_SM_Bed} />
        <mesh geometry={nodes.SM_Bed_3.geometry} material={materials.M_Bed_Wrap} />
        <mesh geometry={nodes.SM_Bed_4.geometry} material={materials.MI_Bed_Fabric_2_SM_Bed} />
        <mesh geometry={nodes.SM_Bed_5.geometry} material={materials.MI_Bed_Fabric_3_SM_Bed} />
        <mesh geometry={nodes.SM_Bed_6.geometry} material={materials.MI_Bed_Pillow_Fabric_2_SM_Bed} />
      </group>
      <mesh geometry={nodes.SM_Coffe_Table_2.geometry} material={materials.M_Coffe_Table_2} position={[-3.7, 0, 3.5]} />
      <group position={[-3.7, 0.4, 3.5]}>
        <mesh geometry={nodes.SM_Decor_6_1.geometry} material={materials.M_Decor_6_leaf} />
        <mesh geometry={nodes.SM_Decor_6_2.geometry} material={materials.M_Decor_6_vase} />
      </group>
      <mesh geometry={nodes.SM_Coffe_Table_3.geometry} material={materials.M_Wall_Marble} position={[3.1, 0, -3.1]} rotation={[Math.PI, -Math.PI / 6, Math.PI]} />
      <mesh geometry={nodes.SM_Opened_Book.geometry} material={materials.M_Opened_Book} position={[3.1, 0.4, -3.1]} rotation={[Math.PI, -0.175, Math.PI]} />
      <mesh geometry={nodes.S_Wooden_Table_viejdi1_lod3_Var1.geometry} material={materials.MI_Wooden_Table_viejdi1_2K} position={[2.061, 0, 2.075]} />
      <mesh geometry={nodes.SM_Ottoman.geometry} material={materials.MI_Ottoman_SM_Ottoman} position={[2.7, 0, -0.1]} />
      <mesh geometry={nodes.ukmlcaoaw_tier_2.geometry} material={materials.MI_ukmlcaoaw} position={[3.161, 0, 2.075]} rotation={[Math.PI, 0, Math.PI]} />
      <group position={[1.061, 0, 2.175]} rotation={[0, Math.PI / 9, 0]}>
        <mesh geometry={nodes.SM_Chair_2_1.geometry} material={materials.M_Tabletop_2} />
        <mesh geometry={nodes.SM_Chair_2_2.geometry} material={materials.M_Chair_2_seat} />
      </group>
      <mesh geometry={nodes.SM_Vase_9.geometry} material={materials.M_Vase_9} position={[1.1, 0, 3.8]} />
      <mesh geometry={nodes.SM_Decor_9.geometry} material={materials.M_Decor_9} position={[4.1, 0.7, 2.2]} />
      <group position={[2.061, 0.7, 2.075]}>
        <mesh geometry={nodes.SM_Kitchen_Decor_9_1.geometry} material={materials.M_Kitchen_Decor_9_Wood} />
        <mesh geometry={nodes.SM_Kitchen_Decor_9_2.geometry} material={materials.M_Kitchen_Ceramic} />
      </group>
      <mesh geometry={nodes.korean_buddha_iron_statue.geometry} material={materials.BMBuddhaKorea01_korean_buddha_iron_statue} position={[0.8, 0.4, -3.5]} rotation={[-Math.PI / 2, 0, -0.175]} scale={0.2} />
      <mesh geometry={nodes.ukkpdhqbw_tier_2.geometry} material={materials.MI_ukkpdhqbw} position={[3.965, 1.634, -0.776]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.SM_uiyvcgffa_tier_2.geometry} material={materials.MI_uiyvcgffa} position={[0, 0, 0.7]} rotation={[0, -Math.PI / 2, 0]} />
      <group position={[0.4, 0, 3.7]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.foshay_bookcase_rack_glb_1.geometry} material={materials.Wood_foshay_bookcase_rack_glb} />
        <mesh geometry={nodes.foshay_bookcase_rack_glb_2.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes.vmjhbix_tier_2.geometry} material={materials.MI_vmjhbix} position={[-0.295, 0.787, 0.691]} rotation={[0, -Math.PI / 2, 0]} />
      <group position={[3.999, 0, 0.184]} rotation={[0, -Math.PI / 2, 0]}>
        <mesh geometry={nodes.SM_System_01_A_1.geometry} material={materials.MI_System_Panel_A} />
        <mesh geometry={nodes.SM_System_01_A_2.geometry} material={materials.MI_System_Panel_B} />
        <mesh geometry={nodes.SM_System_01_A_3.geometry} material={materials.MI_System_Wood} />
      </group>
      <mesh geometry={nodes.SM_System_G_Ladder.geometry} material={materials.MI_System_Metal_Ladder} position={[-1.173, 0, 3.999]} rotation={[0, Math.PI / 2, 0]} />
      <mesh geometry={nodes.SM_Apple_02.geometry} material={materials.MI_Apple_02} position={[-0.41, 1.229, 0.367]} />
      <group position={[-0.655, -0.017, 3.383]} rotation={[0, -0.175, 0]}>
        <mesh geometry={nodes.SM_Books_Mix_6_1.geometry} material={materials['MI_Books_41-45']} />
        <mesh geometry={nodes.SM_Books_Mix_6_2.geometry} material={materials.MI_Books_Sides} />
        <mesh geometry={nodes.SM_Books_Mix_6_3.geometry} material={materials['MI_Books_36-40']} />
      </group>
      <group position={[-1.277, 1.288, 3.999]} rotation={[Math.PI, 0, Math.PI]} scale={3.75}>
        <mesh geometry={nodes.SM_Picture_D_1.geometry} material={materials.MI_Frame_Plastic} />
        <mesh geometry={nodes.SM_Picture_D_2.geometry} material={materials.MI_Frame_Art} />
      </group>
      <group position={[-3.221, 0, 1.604]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.SM_Books_Mix_2_1.geometry} material={materials['MI_Books_31-35']} />
        <mesh geometry={nodes.SM_Books_Mix_2_2.geometry} material={materials['MI_Books_26-30']} />
        <mesh geometry={nodes.SM_Books_Mix_2_3.geometry} material={materials['MI_Books_1-5']} />
        <mesh geometry={nodes.SM_Books_Mix_2_4.geometry} material={materials['MI_Books_6-10']} />
        <mesh geometry={nodes.SM_Books_Mix_2_5.geometry} material={materials['MI_Books_11-15']} />
        <mesh geometry={nodes.SM_Books_Mix_2_6.geometry} material={materials['MI_Books_16-20']} />
        <mesh geometry={nodes.SM_Books_Mix_2_7.geometry} material={materials['MI_Books_21-25']} />
        <mesh geometry={nodes.SM_Books_Mix_2_8.geometry} material={materials['MI_Books_46-50']} />
        <mesh geometry={nodes.SM_Books_Mix_2_9.geometry} material={materials['MI_Books_51-55']} />
        <mesh geometry={nodes.SM_Books_Mix_2_10.geometry} material={materials['MI_Books_56-60']} />
      </group>
      <mesh geometry={nodes.SM_Buddha.geometry} material={materials.MI_Buddha} position={[-3.336, 0, 1.491]} rotation={[Math.PI, -Math.PI / 9, Math.PI]} />
      <mesh geometry={nodes.SM_Box_A.geometry} material={materials.MI_Box_A} position={[-2.294, 0, 1.47]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}

useGLTF.preload('/cozy_home_items_t.glb')
